CREATE TABLE  teams(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL ,
    active BOOLEAN NOT NULL DEFAULT 0,
    cer_id int,
    FOREIGN KEY (cer_id) REFERENCES cer(id) ON DELETE CASCADE ON UPDATE CASCADE
    );
